### ISSUE TITLE
Remove markdown processing from page titles

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire#194]
Hi @lizneely, thanks for posting about this. @swambold1 ran into this issue recently as well. The immediate solution is to use [unicode right single quotation marks](https://unicode-table.com/en/2019/) in place of the apostrophes:

```yaml
title: "O’Keeffe’s Dishes"
```

(These can be typed on a mac keyboard with `Shift-Option-]`.)

Long-term, I'll push a fix for this in future versions of Quire. The problem arises because the page title is being processed Quire's markdown processor which also converts straight apostrophes to curly right single quotation marks. For the `<title>` element through, Quire takes the additional step of stripping out any HTML from the title but is being a little greedy about is and ends up messing up the HTML entity for the single quotation marks as well. The fix I'm going to push will remove all processing altogether so that the title in the page and the browser tab just ends up as it's typed. Regardless of apostrophes or right single quotes. This will also mean that titles with italics will show up as something like `O’Keeffe’s *White Abstraction*`.

_Originally posted by @geealbers in https://github.com/thegetty/quire/discussions/167#discussioncomment-1255408_

**Comment by geealbers** [comment]
This remains an issue in the last version of Quire to use Hugo (0.20.4) but is fixed in newer versions that use 11ty (1.0.0 and above). For users of older, Hugo-versions of Quire, the unicode fix above should be used. Closing this issue.
