### ISSUE TITLE
Caniuse-lite is outdated

### ISSUE THREAD

**Issue by Erin-Cecele** [thegetty/quire#20]
When running 'quire preview' you receive the following message:

**10% building 0/1 modules 1 active ...ire-starter-theme/source/js/application.js** Browserslist: caniuse-lite is outdated. Please run next command `npm update`

You can still preview the project in your browser, so it's not causing any significant issues, but the message creates confusion for users. Running the command 'quire npm update' does not solve the problem. 

<img width="682" alt="Screen Shot 2020-09-01 at 4 39 42 PM" src="https://user-images.githubusercontent.com/62075223/91916389-df4c4a80-ec71-11ea-9484-634db0bb07e5.png">

**Comment by emptyhut** [comment]
Solved this problem thanks to this tip from 1000camels -> 
run this command in themes/default          npx browserslist@latest --update-db

**Comment by geealbers** [comment]
See fix noted above for versions of Quire using Hugo (0.20.4 and below). And is no longer an issue for newer versions of Quire using 11ty (1.0.0 and above).
