### ISSUE TITLE
Pages sometimes failing to render on load

### ISSUE THREAD

**Issue by garrettdashnelson** [thegetty/quire#25]
I'm not sure if this is best tracked here or in `gettypubs/quire-starter-theme`.

I've been noticing a bug with the default theme where page contents sometime fail to render on load. My guess is that the trigger to animate the slide from right is not triggering correctly. Triggering a re-render by opening the navigation menu will successfully show the page contents, as will a hard refresh of the page. 

I'm noticing this behavior primarily in Safari, though it's not reliably replicable. That makes me think that there is some execution based on the timing of an `.onLoad` or a `.ready` function that is not always correctly firing depending on the exact timeline of those page ready states.

Here's an animation showing a page which has failed to render correctly re-rendering when the nav menu is opened. Then, the next page in the catalog also fails to render, and the animation shows how a hard refresh will correct it.

![out](https://user-images.githubusercontent.com/2424901/78664000-225fe880-78a1-11ea-82af-5de53e14224f.gif)

I was going to start digging into the application JS to debug this, but figured I'd check to see if anyone else has noticed this behavior.

**Comment by geealbers** [comment]
Closing this as likely no longer an issue in the latest versions of Quire, and not having further occurrences reported. In the case of a similar issue popping up again in the new version, we'll open a new ticket.
