### ISSUE TITLE
Quicklinks ignores configuration isn't working

### ISSUE THREAD

**Issue by daniel-keller** [thegetty/quire#269]
### Before proceeding, check to make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Steps to reproduce

I've noticed this in our own pre-launch build as well as several other quire publications.
Prefetching through quicklinks is configured to ignore preloading pdfs but it doesn't seem to be working (I suspect the entire ignore list isn't working). As a result I found it more efficient to turn off prefetching (especially if a catalog includes a pdf download in the main navigation).

Here are some examples where prefetching links is auto downloading pdfs in quire:
https://nelson-atkins.org/fpc/seventeenth-century-1600-1699/210/
https://highpoint-editions.netlify.app/catalogue/
https://raykomai.org/catalogue/
https://ad-hoc-museum-collective.github.io/Museum-Digital-Practice-2021/essays/essay-6/

Open dev tools and go to any of the above pages. See that pdfs are downloaded automatically.

### Actual behavior

Prefetching includes pdfs

### Expected behavior

Prefetching should not include pdfs 

### Version numbers

OSX: 12.2
Quire: v0.20.2
Node: v14.18.1

### What browsers are you seeing the problem on?

Chrome

**Comment by geealbers** [comment]
Thanks for posting this. I never forgot it, but we're no longer prefectching assets like this in the Quire v1. So going to close this as an issue with the legacy v0 version that won't get a fix
