### ISSUE TITLE
Template "About" and "Copyright" pages

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire#34]
In previous iterations, we created multiple shortcodes so that users could put together custom About and Copyright pages. However, it was 4 or 5 unique shortcodes and none of them have much use elsewhere outside these pages. So, better to create an `about` page type and build everything into the template. Should also then include a variant `copyright` class or layout option to account for the differences between how this information is typically handled online versus in print.

**Comment by Erin-Cecele** [comment]
This has been addressed in the starter content of projects created with 11ty (Quire v1), so the issue will be closed.
