### ISSUE TITLE
Annoref links are not working in the entry page image viewer

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire#625]
### Before proceeding, check to make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Steps to reproduce

1. Start a new project with version 1.0.0-rc.0
2. Run `quire preview` and visit http://localhost:8080/catalogue/1/
3. Click on any of the text links in the second paragraph

### Actual behavior

There is no response, and the following errors are logged:

<img width="965" alt="Screen Shot 2022-12-12 at 1 00 07 PM" src="https://user-images.githubusercontent.com/7796401/207153384-bc3a05e5-fe8c-493d-95f3-93d9586349cc.png">

### Expected behavior

The links are `{% annoref %}` links and should zoom the main image in the entry viewer to different regions.

### Version numbers

Quire v1.0.0-rc.0
Node v18.12.1
npm 8.19.2
macOS 12.6 Monterey

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by geealbers** [comment]
In progress for v1.0.0-rc.1: https://jira.getty.edu/browse/DEV-13836

**Comment by Erin-Cecele** [comment]
Close with [PR # 11](https://github.com/thegetty/quire-starter-default/pull/11) in the https://github.com/thegetty/quire-starter-default repo.
