### ISSUE TITLE
Links not resolving correctly when project is deployed to a sub-directory rather than root domain

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire#642]
### Discussed in https://github.com/thegetty/quire/discussions/638

<div type='discussions-op-text'>

<sup>Originally posted by **@siobhan559** December 21, 2022</sup>
Hi, I'm at the V&A in London and we're currently working on a prototype of some of our old research journals (and hopefully publishing new research journals in the future) using Quire, and really loving it so far!

I just upgraded to v1.0.0-rc.0 and everything works great locally. However, I'm deploying it to an internal server for QA etc which is where I'm running into a problem. The url we want to use is https://beta.vam.ac.uk**/journals**/<contents> etc but all the links are resolving to https://beta.vam.ac.uk/<contents> for example (and the CSS is also not loaded). 

I know while using the hugo version we had a similar problem which was solved by setting relativeURLs to false in config/site.yml but there doesn't seem to be a similar setting currently. I also had a play around in the eleventy.js file with the HTML base plugin and pathPrefix settings but either my lack of understanding of eleventy or just barking up the wrong tree stopped me from getting anywhere.

</div>

**Comment by geealbers** [comment]
FWIW, I confirmed that `publication.url` was properly set. I also tested it on my own with a deploy of the default starter project to a basic hosting site at https://quire.reclaim.hosting/journal/ which we can see isn't working in the same way @siobhan559 describes above.

**Comment by lizneely** [comment]
Hi! I'm not sure about the community guidelines and if I should be posting here for an update on this bug or on the help forum -- apologies if I'm misstepping! I'm checking in on @cbutcosk / @siobhan559 issues/questions and wonder if there is a timeline for resolution of this issue. We have a 11ty/Quire publication (in English and Spanish) ready to publish and wonder if we need to change our publication URL plans. Thanks, Liz

**Comment by yl5682** [comment]
I am having a similar issue. Even if I set the `url` in `publication.yaml`, all hrefs were not including the custom `url` part; they would start at the root instead. My Quire version is 1.0.0-rc.0. Could you provide some pointers so that I can publish my work soon? @geealbers

**Comment by geealbers** [comment]
Hi @yl5682, our engineers have a fix and I think we'll be able to push a new release early next week. I will post again here as soon as we have that confirmed.

**Comment by geealbers** [comment]
We had it mostly fixed with `.rc.7` and now believe this one is totally fixed with the release of the `1.0.0-rc.8` version of the quire-11ty package. Any new projects started will automatically be the `rc.8` version, with the fix.
