### ISSUE TITLE
Thin horizontal line should not appear above and below figure images in Classic theme

### ISSUE THREAD

**Issue by zsofiaj** [thegetty/quire#700]
### Before proceeding, check to make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Steps to reproduce

I noticed that the design has been slightly updated, and now each figure image has a thin line above and below. Is this something that could be easily removed and reverted back to the old style, which had no line? Erin says there's always been a rule line on the images in the modern theme, the classic theme should not have them. 

### Actual behavior

Thin horizontal line appears above and below the figure images. See examples in this entry:
https://italian-paintings-march2023-updates.netlify.app/catalogue/volume-1/the-florentine-school/4/

### Expected behavior

Thin horizontal lines should not appear in Classic theme, only in Modern theme (per Erin).

### Version numbers

Quire version 1.0.0-rc.3

Node version v18.15.0

**Comment by geealbers** [comment]
This has been fixed with [22c57c0](https://github.com/thegetty/quire-starter-default/commit/22c57c09d39b98c543d2a67a1b05a32cba03e097) in the `quire-starter-default` repo, and will be available in all newly started Quire projects from this point forward.

Thanks for reporting it @zsofiaj!
