### ISSUE TITLE
EPUB dcterms:modified tag is left empty and causing a validation issue

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire#716]
### Before proceeding, check to make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Steps to reproduce

1. Start a new Quire project
2. Run `quire build` and then `quire epub` to create the EPUB file
3. Run the EPUB through epubcheck with `java -jar path/to/epubcheck.jar patt/to/epubjs.epub`

### Actual behavior

The package.opf file that epub.js is generating includes a `<meta property="dcterms:modified"></meta>` element, but it's empty and this is causing an EPUB validation error. We need to either provide a modified date here, or remove the empty tag. If the date is added, it must follow the standard syntax: "CCYY-MM-DDThh:mm:ssZ"

In our `_epub/manifest.json` file, we're providing `"dateModifed": "2022-12-01T00:00:00.000Z",` @fchasen is that not correct?

### Expected behavior

The `dcterms:modified` tag has the date given, or is not included at all in the OPF file

### Version numbers

quire-cli 1.0.0-rc.6
quire-11ty 1.0.0-rc.8
node 18.12.1

**Comment by fchasen** [comment]
We are passing `date` instead of `dateModified` in the JSON - updating both to work.
