### ISSUE TITLE
EPUB an extra <itemref> is being added to the spine in package.opf and causing a validation issue

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire#717]
### Before proceeding, check to make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Steps to reproduce

1. Start a new Quire project
2. Run `quire build` and then `quire epub` to create the EPUB file
3. Run the EPUB through epubcheck with `java -jar path/to/epubcheck.jar patt/to/epubjs.epub`

### Actual behavior

An extra `<itemref>` is being added to the spine in package.opf, that doesn't resolve to an actual page and so is causing a validation error. It's the first item in the list and doesn't correspond to anything I can see in the manifest.json file.

```html
<itemref idref="id_" linear="no"/>
```

@fchasen is this maybe meant to be a cover page/file, and so potentially related to issue #715?

### Expected behavior

There should be this extra item or it should resolve to a page/resource.

### Version numbers

quire-cli 1.0.0-rc.6
quire-11ty 1.0.0-rc.8
node 18.12.1

**Comment by fchasen** [comment]
Thanks, removed!
