### ISSUE TITLE
EPUB pages with SVGs need `properties="svg"` added in manifet

### ISSUE THREAD

**Issue by geealbers** [thegetty/quire#719]
### Before proceeding, check to make sure there isn’t an existing issue for this bug.

- [X] I have searched the existing issues and determined this is a new bug.

### Steps to reproduce

1. Start a new Quire project
2. Run `quire build` and then `quire epub` to create the EPUB file
3. Run the EPUB through epubcheck with `java -jar path/to/epubcheck.jar patt/to/epubjs.epub`

### Actual behavior

Our copyright page includes an `SVG` for the creative commons license. EPUB wants that declared in the package.opf file and is otherwise throwing a validation error.

@fchasen do we need to indicate in the `manifest.json` file we're feeding epub.js which pages have SVGs, or is epub.js supposed to figure this out?

### Expected behavior

The presence of an SVG on any page should be recorded in the pakage.opf file as in this example:

```html
<item id="id_03_pdf-epub-copyright" href="03_pdf-epub-copyright.xhtml" media-type="application/xhtml+xml" properties="svg" />
```

### Version numbers

quire-cli 1.0.0-rc.6
quire-11ty 1.0.0-rc.8
node 18.12.1

**Comment by fchasen** [comment]
Properties can be pass down on `readingOrder` items by adding an array of properties like below:

```json
 "readingOrder": [
        {
            "url": "content/titlepage.html",
            "properties": ["svg"]

        }
]
```

**Comment by Erin-Cecele** [comment]
Closing because this is duplicated in #780
